<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Plaintext</AssemblyName>
    <RootNamespace>Plaintext.Windows</RootNamespace>
    <ApplicationIcon>Assets/Plaintext.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets/Fonts/*.ttf" />
    <None Include="../LICENSE" Link="LICENSE" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../THIRD_PARTY_NOTICES.md" Link="THIRD_PARTY_NOTICES.md" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../ThirdPartyLicenses/*.txt" Link="ThirdPartyLicenses\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
